### ISSUE TITLE
Startup errors

### ISSUE THREAD

**Issue by Trsmorales** [Trsmorales/td-pubg#1]
Resolve these
Thu, 30 Nov 2017 05:21:40 GMT express-session deprecated undefined resave option; provide resave option at app.js:37:9
Thu, 30 Nov 2017 05:21:40 GMT express-session deprecated undefined saveUninitialized option; provide saveUninitialized option at app.js:37:9

**Comment by Trsmorales** [comment]
Resolved via 71643b0ad67f4a10a95ca4c3d7adcce19f8f7765
